name: angular_components
version: 1.0.3
description: >
  The official Material Design components for AngularDart. Used at Google in
  production apps.
repository: https://github.com/angulardart/angular_components
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.0
  angular_forms: ^4.0.0
  async: ^2.8.2
  build: ^2.1.0
  build_config: ^1.0.0
  built_collection: ^5.1.0
  collection: ^1.15.0
  fixnum: ^1.0.0
  intl: ^0.17.0
  js: ^0.6.3
  logging: ^1.0.1
  meta: ^1.7.0
  observable: # Please Google just publish it!!!
    git:
      url: https://github.com/google/observable
  protobuf: ^2.0.0
  quiver: ^3.0.1
  sass_builder: ^2.1.4

dev_dependencies:
  path: ^1.8.0
  lints: ^1.0.0
  test: ^1.17.11
