name: Dart CI

on:
  push:
    branches:
      - compatible
      # - dev
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  analyze:
    name: Analyze Dart files
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1.3
      - uses: actions/checkout@v2.3.4
      - name: Analyze files
        run: dart analyze