name: Gallery CI
on:
  push:
    branches:
      - compatible
  pull_request:
    branches:
      - compatible
defaults:
  run:
    shell: bash

jobs:
  build_gallery:
    name: Build AngularDart Gallery
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        sdk: [stable, 2.14.0]
    steps:
      # Maybe add caching? I'll have to see how long it takes.
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: ${{ matrix.sdk }}
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: Fetch dependencies
        working-directory: examples/angular_components_example
        run: dart pub get && dart pub global activate webdev
      - name: Build gallery
        working-directory: examples/angular_components_example
        run: dart pub global run webdev build